// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://asgigsiztwksvnkwpzad.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFzZ2lnc2l6dHdrc3Zua3dwemFkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkyODUzOTgsImV4cCI6MjA2NDg2MTM5OH0.iiDq-MMOYdNdmpiG3X7kHy3ZuAzTWiVi44Vm4J46-Rc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
